# Generated by Django 5.2.17 on 2026-09-10 11:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('issuer', models.CharField(max_length=140)),
                ('issue_date', models.DateField()),
                ('credential_url', models.URLField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', '-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=180)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=160)),
                ('institution', models.CharField(max_length=160)),
                ('location', models.CharField(max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Education',
                'ordering': ['display_order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('company', models.CharField(max_length=140)),
                ('location', models.CharField(max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('responsibilities', models.TextField(help_text='One responsibility per line')),
                ('technologies', models.CharField(help_text='Comma-separated', max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.CharField(max_length=220)),
                ('description', models.TextField()),
                ('features', models.TextField(help_text='One feature per line')),
                ('technologies', models.CharField(help_text='Comma-separated', max_length=255)),
                ('github_url', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='projects/')),
                ('accent', models.CharField(default='#3ee0b1', max_length=20)),
                ('is_featured', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='code', max_length=40)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='[YOUR NAME]', max_length=120)),
                ('title', models.CharField(default='Python Developer', max_length=160)),
                ('tagline', models.CharField(default='I build reliable backend systems, REST APIs, and clean Django applications.', max_length=255)),
                ('about_intro', models.TextField(default='I am a Python/Django developer focused on backend architecture, REST APIs, and production-ready web applications. I care about clear models, maintainable views, and interfaces that feel considered.')),
                ('about_details', models.TextField(default='My work spans authentication, CRUD workflows, database design, and API integrations. I write readable Python, structure Django apps for long-term maintenance, and ship with deployment in mind.')),
                ('email', models.EmailField(default='[YOUR EMAIL]', max_length=254)),
                ('phone', models.CharField(default='[YOUR PHONE]', max_length=80)),
                ('location', models.CharField(default='[YOUR LOCATION]', max_length=120)),
                ('github_url', models.URLField(default='https://github.com/[YOUR GITHUB]')),
                ('linkedin_url', models.URLField(default='https://linkedin.com/in/[YOUR LINKEDIN]')),
                ('resume_file', models.FileField(blank=True, upload_to='resume/')),
                ('years_experience', models.PositiveIntegerField(default=3)),
                ('projects_completed', models.PositiveIntegerField(default=12)),
                ('technologies_count', models.PositiveIntegerField(default=18)),
                ('github_contributions', models.PositiveIntegerField(default=800)),
                ('github_repos', models.PositiveIntegerField(default=24)),
                ('github_stars', models.PositiveIntegerField(default=48)),
                ('availability', models.CharField(default='Open to full-time roles, freelance, and contract work', max_length=120)),
                ('meta_description', models.CharField(default='Python & Django developer portfolio — backend systems, REST APIs, and production web applications.', max_length=220)),
            ],
            options={
                'verbose_name': 'Site profile',
                'verbose_name_plural': 'Site profile',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('category', models.CharField(choices=[('programming', 'Programming'), ('backend', 'Backend'), ('database', 'Database'), ('tools', 'Tools'), ('deployment', 'Deployment')], max_length=32)),
                ('proficiency', models.PositiveSmallIntegerField(default=80)),
                ('icon', models.CharField(blank=True, help_text='Optional icon keyword', max_length=40)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'display_order', 'name'],
            },
        ),
    ]
